generic json rich ui
activeprospect/leadconduit-integration-json pull request #5
Opened 2021-06-07 19:46 UTC by jgrayson676

## Description of the change

adds an RUI for the json integration

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change
- [ ] Technical Debt
- [ ] Documentation

## Related tickets

https://app.clubhouse.io/active-prospect/story/11332/update-generic-json-rui

## Checklists

### Development and Testing

- [ ]  Lint rules pass locally.
- [ ]  The code changed/added as part of this pull request has been covered with tests, or this PR does not alter production code.
- [ ]  All tests related to the changed code pass in development, or tests are not applicable.

### Code Review

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached.
- [ ]  At least two engineers have been added as "Reviewers" on the pull request.
- [ ]  Changes have been reviewed by at least two other engineers who did not write the code.
- [ ]  This branch has been rebased off master to be current.

### Tracking 
- [ ]  Issue from Clubhouse has a link to this pull request.
- [ ]  This PR has a link to the issue in Clubhouse.

### QA
- [ ]  This branch has been deployed to staging and tested.

2021-06-09 18:35 UTC, cgrayson requested changes
Some UX changes to make on this, as discussed offline. 🙇

2021-06-21 16:52 UTC, jgrayson676 commented on package.json
> +    "leadconduit-sanitize-name": "^1.0.2",
I wonder if it's worth adding this to the `dev-dependencies` package, any recipient integration with a rui uses it.

2021-06-22 20:34 UTC, cgrayson approved these changes
Otherwise LGTM

2021-06-22 20:34 UTC, cgrayson commented on package.json
> +    "leadconduit-sanitize-name": "^1.0.2",
Good idea 😁 Now that we added it, you can take this out.

2021-06-22 20:34 UTC, cgrayson commented on package.json
> +    "@activeprospect/integration-components": "^2.0.0",
I still wonder about if we could get away with everything that ends up webpack'd as a `devDependency`, but when I've used `integration-components` I've made it a production `dependency`.

2021-06-22 21:02 UTC, jgrayson676 commented on package.json
> +    "@activeprospect/integration-components": "^2.0.0",
I don't mind changing it, but it seems to have worked fine in staging at least

2021-06-23 19:56 UTC, cgrayson approved these changes
LGTM

2021-06-23 20:24 UTC, merged